---
title: "Circ_RNAs"
author: "Franco"
date: "2024-08-19"
output: html_document
---

```{r}
library(tidyverse)
library(conflicted)
conflict_prefer("filter", "dplyr")
conflict_prefer("desc", "dplyr")
conflict_prefer("select", "dplyr")
conflict_prefer("slice", "dplyr")
conflict_prefer("rename", "dplyr")
conflict_prefer('intersect', 'dplyr')
conflict_prefer("count", "dplyr")

if (rstudioapi::isAvailable()) {
  setwd(dirname(rstudioapi::getActiveDocumentContext()$path))
}
```


```{r}
res_df <- read_tsv("./CircRNA/circ_spike_NAFLD_Diagnosis_AMC.tsv")

res_df = res_df %>%
  mutate(diffexpressed = "NO") %>%
  mutate(diffexpressed = ifelse(log2FoldChange > 0.6 & padj < 0.05, "UP", diffexpressed)) %>%
  mutate(diffexpressed = ifelse(log2FoldChange < -0.6 & padj < 0.05, "DOWN", diffexpressed)) %>%
  mutate(label_on = NA) %>%
  mutate(label_on = ifelse(diffexpressed == "NO", NA, gene_name))
```

```{r}
sig_genes_circ <- as.data.frame(subset(res_df, padj < 0.05 & abs(log2FoldChange) > 2))

write_csv(sig_genes_circ, "./CircRNA/difsig.csv")
```


```{r}
ev2 <- EnhancedVolcano(res_df, lab=res_df$label_on,
                      labSize = 1.5,
                      title = 'circRNA', titleLabSize = 10,
                      subtitle = "NAFLD vs Control", subtitleLabSize = 8,
                      x= "log2FoldChange", y="padj",
                      xlab = bquote(~Log[2]~ 'fold change'),
                      ylab = bquote(~-Log[10]~adjusted~italic(P)),
                      caption = bquote(~Log[2]~ "fold change cutoff: 1; p-value cutoff: 0.05"), captionLabSize = 7,
                      axisLabSize = 8,
                      pCutoff = 0.05, FCcutoff = 2.0,
                      pointSize = 1,
                      #legend=c('NS','FC>2','p-adj<0.05', 'p-adj<0.05 & FC>2'),
                      colAlpha = 0.8,
                      gridlines.major = F, gridlines.minor = F,
                      xlim=c(-4,4), ylim=c(0,4),
                      col=c('darkgray', "#5bb75b", "#428bca", "#e35d6a"),
                      legendPosition = 'bottom',legendLabSize = 7,
                      drawConnectors = TRUE,
                      widthConnectors = 0.3,
                      colConnectors = 'black',
                      arrowheads = F)

ggsave(paste0(data_dir, "./Figures/circRNA_NAFLD_C1.pdf"), ev2, dpi = 500)
ev2
```




