---
title: "Cleaning_annotation"
author: "Franco"
date: "2025-07-07"
output: html_document
---

## Load annotation
```{r}
library(dplyr)
library(readxl)
library(stringr)
```

```{r}
ann1 <- read.csv("./Data/Suplementary_Table1.csv") 
```

```{r}

df<- ann1
# 1. Define a character vector of all the variables you want to keep:
vars_to_keep <- c(
  # --- Clinical characteristics of patients ---
  "SMAPLE_RNA", "Gender", "Sex", "Age", "Ethnicity",
  "Height_cm", "Weight_kg", "WaistCirc_cm", "HipCirc_cm", "BMI",
  "Date_LocalLab", "Count_RBC", "Count_Platelets", "Count_Leucocytes",
  "Count_Neutrophils", "Count_Lymphocytes", "Count_Monocytes",
  "Count_Eosinophils", "Count_Basophils", "Hematocrit_pct", "ESR_mmph",
  "Hb_gpL", "INR", "Creatinine_mgpdL", "eGFR", "Ureum_mgpdL",
  "Na_mM", "K_mM", "MgSerum_mM", "MgRBC_mM", "Cl_mM", "HCO3_mM",
  "AnionGap_mM", "Calcium_mM", "Phosphate_mM",
  "GlcFluorideFasted_mgpdL", "GlcSerumFasted_mgpdL", "Urate_mgpdL",
  "CRP_mgpL", "CRPHs_mgpL", "HBA1c_pct", "ProtTot_gpL", "LDH_UpL",
  "CK_UpL", "AST_UpL", "ALT_UpL", "AP_UpL", "GGT_UpL",
  "ALT_PreviouslyNormal", "ALT_PreviouslyNormal_Times",
  "Lipase_UpL", "S-cholinesterase_UpL",
  "BilirubinTot_mgpdL", "BilirubinConj_mgpdL", "BilirubinUnconj_mgpdL",
  "TG_mgpdL", "CholTot_mgpdL", "CholHDL_mgpdL", "CholLDL_mgpdL",
  "Homocystein_uM", "Fe_pgpdL", "TIBC_ugpdL", "TransferrinSaturation_pct",
  "Ferritin_ugpL", "FolateSerum_ugpL", "FolateRBC_ugpL", "VitB12_ngpL",
  "Albumin_gpL", "ElektrophoresisAbnormal", "ElektrophoresisInfo",
  "InsulinSerumFasted_pM", "C-peptideFasted_nM", "IGF1_ngpmL",
  "VitDOH_ngpmL", "Cortisol_ngpmL", "AFP_ugpL",
  "IgG_gpL", "IgA_gpL", "IgM_gpL", "A1AT_gpL", "Ceruloplasmin_gpL",
  "Cu_mgpL", "Haptoglobin_gpL", "TransferrinCDT_pct",
  "HAV_IgM", "HBV_sAg", "HBV_cAb", "HCV_Ab",
  "US_steatosis", "US_attenuation", "US_Saverymuttu_grade",
  "US_evidencecirrhosis", "US_ascites", "US_gallstones",
  "US_nodule", "US_splenomegaly",
  "FS_remark", "FS_probe", "FS_measurements", "FS_validmeasurements",
  "FS_kPa", "FS_IQR_kPa", "FS_IQRmedian_pct", "FS_CAP_dbpm",
  "SWE_avg", "NFS", "FIB_4", "APRI",
  # --- Disease state ---
  "ChildPugh", "PortalHypertension", "AscitesOrTreated",
  "EncephalopathyOrTreated",
  # --- Diagnosis (coded) ---
  "NAFLD_Diagnosis", "NAFLD_Diagnosis_AMC",
  "NASH_Diagnosis", "NASH_Diagnosis_AMC",
  "SAF_Algo", "SAF_Algo_AMC",
  "NASH_Atrisk", "NASH_Atrisk_AMC",
  "NAScutoff", "NAScutoff_AMC",
  "BPS_Cirrhosis", "BPS_Cirrhosis_AMC",
  "FIBcutoff", "FIBcutoff_AMC",
  # --- Clinical diagnoses (working, non‐coded) ---
  "T2DM", "Hypertension",
  "DyslipidemiaTG", "DyslipidemiaChol",
  "Hypothyroidism", "OSA_ObstructiveSleepApnoea",
  "Gallstones", "Cirrhosis", "Malignancy",
  # --- Pathology ---
  "BPS_NAFLDdiag", "BPS_NAFLDdiag_num",
  "BPS_steatosis", "BPS_ballooningSAF",
  "BPS_lobularinflammation", "BPS_fibrosisBrunt",
  "BPS_NAS", "BPS_SAF_Activity",
  "BPS_AMC_lenght_mm", "BPS_AMC_fragments",
  "BPS_AMC_quality", "BPS_AMC_steatosis",
  "BPS_AMC_steatosis_microvesiculair",
  "BPS_AMC_lobularinflammation", "BPS_AMC_portalinflammation",
  "BPS_AMC_ballooningKleiner", "BPS_AMC_NAS",
  "BPS_AMC_ballooningSAF", "BPS_AMC_fibrosisBrunt",
  "BPS_AMC_fibrosisEPOS", "fibrosis", "fibrosis_AMC",
  "fibrosis_EPOS",
  # --- Exposures ---
  "T2DM_treatment", "Hypertension_treatment",
  "DyslipidemiaTG_treatment", "DyslipidemiaChol_treatment",
  "Hypothyroidism_treatment", "OSA_treatmentCPAP",
  "Gallstones_cholecystectomy", "Bariatric",
  "Drugs_antihyperglycemic", "Drugs_LipidLowering_Statin",
  "Drugs_Lipidlowering_Fibrate", "Drugs_Hypertension",
  "Drugs_Insulin", "Substance_Alcohol", "Substance_Smoking"
)

# 2. Select only those columns from your data.frame (here assumed named `df`)
df_selected <- df %>%
  select(any_of(vars_to_keep))

# 3. (Optional) Check which requested vars were actually present:
missing_cols <- setdiff(vars_to_keep, names(df_selected))
if(length(missing_cols)>0){
  warning("These columns were not found in df: ", paste(missing_cols, collapse = ", "))
}

indirect <- c("Sex", "Age", "Ethnicity", "Date_LocalLab")

ann1_noIDs <- df_selected %>% dplyr::select(!indirect)
write.csv(ann1_noIDs, "./Data/SupTable1_NoIDs.csv")
# Your df_selected now contains exactly the BRISQ‐relevant columns.
```

### CLEAN DATA
 
```{r}
ann2 <- read.csv("./Data/Suplementary_Table2.csv")
ann2_chem <- read_xlsx("Data/fulldataset.xlsx", 
                       sheet = "Sheet1",   # or the name/index of the sheet you want
                       na = c("", "NA"))

ann2_chem_filt<- ann2_chem[-817,] ##removing wrong annotation

vars_to_keep<-c("Sample_ID", "EndstageLD",                    
"ChildPugh", "Diagnosis_Remarks","Elastography","Elastography_Dt",               
"Elastography_Dt_Accuracy", "Elastography_Equipment","Elastography_Probe","Elastography_Stiffness_kPa",    
"Elastography_Stiffness_kPa_IQR" ,"Elastography_Measurements","Elastography_CAP","Elastography_CAP_IQR",          
"Elastography_Remarks" ,"BMI","BPS_Date","BPS_ID_hospital_alt",           
"BPS_quality" ,"BPS_steatosis","BPS_steatosis_microvesicular","BPS_lobinflam",                 
"BPS_portinflam","BPS_ballooningKleiner","BPS_NAS","BPS_ballooningSAF",             
"BPS_fibrosisBrunt","BPS_fibrosisBrunt_F1subdiv","BPS_fibrosisEpos","BPS_fibrosisEpos_F6subdiv",     
"Comment","NASH_atrisk_routine","NASH_atrisk_BPS","NASH_Bedossa"
)
ann2_chem_filt <- ann2_chem_filt %>%
  select(any_of(vars_to_keep))



ser_plas <- read.csv("./Data/serumPlasma_ids.csv")

ann2_tmp <- ann2 %>% left_join(ser_plas, by=c("PlasmaID"="prlnkid_pla"))
ann2_filt<- ann2_tmp#[-809,] ##removing wrong annotation

ann2_full <- ann2_filt %>% left_join(ann2_chem_filt, by=c("prlnkid_ser"="Sample_ID"))

ann2_clean <- ann2_full %>%
  # 1) drop all columns ending in “.y”
  select(-ends_with(".y")) %>%
  # 2) strip trailing “.x” from whatever’s left
  rename_with(~ str_remove(., "\\.x$"))

write.csv(ann2_clean, "./Data/SupTable2_WithIDs.csv")


##Removing Direct and indirect identifiers

direct <- c("Subject_ID", "PlasmaID", "prlnkid_ser", "BPS_ID_hospital_alt")

indirect <- c("YearBirth", "Race", "Hospital", "Elastography_Dt", "Elastography_Dt_Accuracy", "BPS_Date", "Diagnosis_Dt", "Diagnosis_Dt_Accuracy", "ClinChem_Dt", "Sample_Dt")
```

```{r}
ann2_noIDs <- ann2_clean %>% dplyr::select(!direct) %>% dplyr::select(!indirect)
write.csv(ann2_noIDs, "./Data/SupTable2_NoIDs.csv")
```

```{r}

```

 
 