---
title: "09_Manuscript_Retro"
author: "FrancoPoma"
date: "2024-06-21"
output: html_document
---

```{r}
knitr::opts_chunk$set(warning=FALSE, message=FALSE)

if (rstudioapi::isAvailable()) {
  setwd(dirname(rstudioapi::getActiveDocumentContext()$path))
}

require(dplyr)
require(tidyverse)
require(ggbeeswarm)
require(biomaRt)
require(readxl)
require(DESeq2)
require(EnhancedVolcano)
require(ggpubr)
library(conflicted)

conflict_prefer("filter", "dplyr")
conflict_prefer("desc", "dplyr")
conflict_prefer("select", "dplyr")
conflict_prefer("slice", "dplyr")
conflict_prefer("rename", "dplyr")
conflict_prefer('intersect', 'dplyr')
conflict_prefer("count", "dplyr")

color_panel<-c("#e35d6a","#428bca","darkgray","#e87810","#5bb75b", "#23496b","#ffbf00","#cc2028","#039748","pink","gray")
theme_point<-theme_bw()+theme(strip.background = element_blank())

theme_bar<-theme_bw()+theme(axis.text.x = element_text(angle=90, vjust=0.5, hjust=1),strip.background = element_blank(),axis.ticks.x = element_blank(),axis.line.x = element_blank())
theme_boxplot<-theme_classic()+theme(axis.text.x = element_text(angle=90, vjust=0.5, hjust=1),strip.background = element_blank(),axis.ticks.x = element_blank(),axis.title.x = element_blank(),axis.line.x = element_blank(),legend.position = "none")

data_dir <- "./Data/"
#annotation
ann_retro<-read_csv(paste0(data_dir,"annotation_Cohort1.csv"))
```



```{r}
#getting gene annotation
ensembl <- useEnsembl("ensembl",dataset="hsapiens_gene_ensembl", version = 109)
genes_ens <- getBM(attributes=c('ensembl_gene_id','gene_biotype','chromosome_name'),mart=ensembl)
htseq_C1 <- read_delim(paste0(data_dir, "/htseq_cohort1.txt"))
htseq <- htseq_C1 %>% filter(!str_detect(ensembl_gene_id, "^__"))

htseq <- htseq  %>%
  column_to_rownames("ensembl_gene_id")

count_table_NASH <- htseq %>% dplyr::select(ann_retro$SMAPLE_RNA)

count_table_NASH <- count_table_NASH  %>%
  rownames_to_column("ensembl_gene_id")

#Get sum of sequin counts
Spikes_C1<- read.csv(paste0(data_dir, "/SpikeRatio_C1.csv"))
Spikes_C1<-Spikes_C1 %>% column_to_rownames(var = "RNAID")
Seq_counts <- as.data.frame(t(Spikes_C1[c("Sequin")]))
Seq_counts <- Seq_counts %>% dplyr::select(colnames(count_table_NASH)[2:length(count_table_NASH)])

#remove spikes from data
count_table_NASH_noSpike <- count_table_NASH %>% filter(ensembl_gene_id %in% grep("^R|^ERCC", count_table_NASH$ensembl_gene_id, invert=T,value=T))

count_table_NASH_noSpike <- count_table_NASH_noSpike  %>%
  column_to_rownames("ensembl_gene_id")

#pheno data filtered

pDat_NASH <- ann_retro %>% column_to_rownames(var='SMAPLE_RNA')
summary(as.factor(pDat_NASH$NAFLD_Diagnosis_AMC))

```

```{r}
#Cleaning col DATA
pDat_NASH_filt<-pDat_NASH[!is.na(pDat_NASH$NAFLD_Diagnosis_AMC),]
pDat_NASH_filt<-pDat_NASH[!is.na(pDat_NASH$Cirrhosis),]
pDat_NASH_filt$Gender<-as.factor(pDat_NASH_filt$Gender)

pDat_NASH_filt$Cirrhosis<-as.factor(pDat_NASH_filt$Cirrhosis)
pDat_NASH_filt$NAFLD_Diagnosis_AMC<-as.factor(pDat_NASH_filt$NAFLD_Diagnosis_AMC)

Seq_counts_select <- dplyr::select(Seq_counts, row.names(pDat_NASH_filt))
count_table <- count_table_NASH_noSpike %>%  dplyr::select(rownames(pDat_NASH_filt))

dds_spike <- DESeqDataSetFromMatrix(countData=count_table, colData = pDat_NASH_filt, design= ~Cirrhosis + Gender)
#QC Filtering
smallestGroupSize <- 30
keep <- rowSums(counts(dds_spike) >= 10) >= smallestGroupSize
dds_spike <- dds_spike[keep,]
#Normalization base on sequin counts
sizeFactors(dds_spike) <- estimateSizeFactorsForMatrix(Seq_counts_select)
dds_spike <- DESeq(dds_spike)
```



```{r}
#Contrast of interest
res_spike2 <- results(dds_spike, contrast = c("Cirrhosis", "1", "0"), alpha = 0.05)
resOrdered2 <- as.data.frame(res_spike2) %>%
  rownames_to_column(var = "ensembl_geneID") %>%
  dplyr::arrange(desc(abs(log2FoldChange))) 

#Filter only significant genes
sig_genes_M2 <- as.data.frame(subset(res_spike2, padj < 0.01 & abs(log2FoldChange) > 2))

#Write results
write.table(resOrdered2,file=paste0(data_dir ,"Genes_SexCirrhosis_sequin_C1.txt"), row.names = F, sep = "\t", quote=F)

#addd gene symbols to the data
genes_ens1 <- getBM(attributes=c('ensembl_gene_id','hgnc_symbol', 'entrezgene_id', 'gene_biotype'),mart=ensembl)
sig_genes_M2_symbol <- sig_genes_M2 %>% rownames_to_column(var='ensembl_gene_id')
sig_genes_M2_symbol <- left_join(sig_genes_M2_symbol , genes_ens1, by="ensembl_gene_id", multiple='any')
resOrdered_symbol2 <- left_join(resOrdered2 , genes_ens1, by=c("ensembl_geneID"="ensembl_gene_id"))
```

```{r}
#Volcano plot
ev2 <- EnhancedVolcano(resOrdered_symbol2, lab= ifelse(resOrdered_symbol2$hgnc_symbol!="",resOrdered_symbol2$hgnc_symbol, resOrdered_symbol2$ensembl_geneID),
                      labSize = 1.5,
                      title = 'Cirrhosis diagnosis', titleLabSize = 10,
                      subtitle = "Presence vs Absence", subtitleLabSize = 8,
                      x= "log2FoldChange", y="padj",
                      xlab = bquote(~Log[2]~ 'fold change'),
                      ylab = bquote(~-Log[10]~adjusted~italic(P)),
                      caption = bquote(~Log[2]~ "fold change cutoff: 1; p-value cutoff: 0.05"), captionLabSize = 7,
                      axisLabSize = 8,
                      pCutoff = 0.01, FCcutoff = 2.0,
                      pointSize = 1,
                      #legend=c('NS','FC>2','p-adj<0.05', 'p-adj<0.05 & FC>2'),
                      colAlpha = 0.8,
                      gridlines.major = F, gridlines.minor = F,
                      xlim=c(-4,4), ylim=c(0,4),
                      col=c('darkgray', "#5bb75b", "#428bca", "#e35d6a"),
                      legendPosition = 'bottom',legendLabSize = 7,
                      drawConnectors = TRUE,
                      widthConnectors = 0.3,
                      colConnectors = 'black',
                      arrowheads = F)

ev2
```

```{r}
ggsave("./Figures/Genes_Cirrhosis_C1.pdf", ev1.1, dpi = 500)
```

```{r}
#load sets from papers
# Sets from Divya Ramnath paper
set_LivFib <- c(
"EFEMP1","CFTR","LUM","PLCXD3","THBS2","LTBP2","CD24","AEBP1","DTNA","VWF","LAMA2","VCAN","MMP2","KRT7","Spp1","NFASC","COL1A2","MAP1B","PDGERA","COL5A1","COL1A1","SLC12A2",'JAG1','IL7R','FAT1','FBN1','ITGAV','ANXA2','GUCY1A3','SLC6A6','CLEC4M','MAML2','LAMB1','CAPN2','ABCC4','MYO5A','ECN2','MT1E','PPP1R1A','MT1M','IGFALS','TTC36','CYBRD1','OSMR','CRIM1','PODN','MUC6','PLXDC2')

steatosis_set <- c(
'FSTL1',
'VWF',
'CRIM1',
'SPRY1',
'MAP1B',
'AQP1',
'FRAS1',
'ADAMTS1',
'PLXDC2',
'COL1A2'
)

#from meta analysis
report_genes <- read_xls("./Resources/41598_2017_10930_MOESM2_ESM.xls", sheet = "Agreement_with_nonparam", skip=2)

lncRNA_NASH <- c("NEAT1",
"MEG3",
"MALATI",
"ENST00000413567",
"ENST00000413567",
"ENST00000548691",
"uc001gvp.1",
"TCONS_00025733",
"uc.372",
"uc.94",
"uc.157",
"B4GALT1-ASI",
"IncARSR",
"RP11-279F6.1",
"AC004540.4",
"uc.333",
"CCATI",
"RABGAPILDT-206",
"lnc-SPARCLI-1:2",
"lnc PVT1",
"lnc HCG18",
"LINC00240",
"has_circ_0046367",
"circRNA_0001805",
"APOA4-AS",
"NEAT1",
"RP11-484N16.1",
"MEG3",
"lncTNF",
"MALAT1",
"lnc18q22.2",
"NEAT1",
"MEG3",
"MALAT1",
"MEG3",
"HULC",
"circRNA SCAR",
"GAS5",
"MALATI",
"lncPRYP4-3",
"lncPRYP4-4",
"LeXis",
"hsa_circ_0089763",
"H19",
"RP11-128N14.5",
"hsa_circ_0008882",
"TGFB2/TGFB2-",
"TGFB2/TGFB2-OTI hsa_circ_0008882",
"OTI",
"lncPRYP4-3",
"hsa_circ 0022430",
"lnc-SPARCL1-1:2",
"lnc-SPARCL1-1:2",
"hsa_circ_0032777",
"RABGAPILDT-206",
"hsa_circ_0141729",
"206",
"lncPRYP4-3",
"hsa_circ_0001311",
"HULC",
"MAPKAPK5-ASI",
"hsa_circ_0045989",
"LINC01638",
"XLOC_003146",
"RP11_20J153",
"HCC",
"LncRNA FTX",
"lncRNA SNHG20")

```

```{r}
sig_genes_M1_symbol<- sig_genes_M2_symbol %>% mutate(Reported = case_when(hgnc_symbol %in% set_LivFib ~ "Fibrosis",
                                                                          hgnc_symbol %in% report_genes$GeneSymbol ~ "Liver_disease",
                                                                          hgnc_symbol %in% steatosis_set ~ "Steatosis"))

reported_sig <- sig_genes_M1_symbol %>% dplyr::filter(!is.na(sig_genes_M1_symbol$Reported))

reported_sig_info <- report_genes %>% filter(report_genes$GeneSymbol%in% reported_sig$hgnc_symbol)

write_excel_csv(sig_genes_M1_symbol,file=paste0(data_dir ,"DEG_NAFLD_sequin_C1.csv"))
```

# GSEA

## Hallmark

```{r, echo=FALSE, message=FALSE, warning=FALSE}
library(msigdbr)
H <- as.data.frame(msigdbr(species = "Homo sapiens", 
                           category = "H"))

###Formatting the database###
H.ensembl.ls <- H %>% 
  #Keep gene ID that match expression data gene ID
  dplyr::select(gs_name, ensembl_gene) %>% 
  #Collapse all genes in each gene set into 1 row each
  group_by(gs_name) %>%
  summarise(all.genes = list(unique(ensembl_gene))) %>%
  #Convert to list
  deframe()
```

```{r}
###`fgsea` requires our fold changes to be in a decreasing, named vector (or list of vectors if you have multiple groups). So we format as a vector for our one group of TB-MEDIA fold changes.###
#Vector of mean fold change values
FC.vec <- resOrdered2$log2FoldChange
#Add names
#Importantly, since both columns come from the same data frame,
#we are confident that they are in the same order
names(FC.vec) <- resOrdered2$ensembl_geneID
```

```{r}
#GSEA calculates significance differently if you have only positive (`pos`), only negative (`neg`), or mixed (`std`) fold change values. This is analogous to a one- vs two-tailed t-test. 

#We can set this by-hand by checking our minimum and maximum fold changes. We see we have positive and negative, thus our type is `std`.

#code to select the score type
if(min(FC.vec) < 0 & max(FC.vec) > 0){
        scoreType <- "std"
      } else if(max(FC.vec) <= 0){
        scoreType <- "neg"
      } else if(min(FC.vec) >= 0){
        scoreType <- "pos"
      } else{
        stop("Could not determine score type from fold changes.")
      }
```

```{r}
#GSEA
library(fgsea)

fgseaRes <- fgsea(pathways = H.ensembl.ls, 
                  stats    = FC.vec,
                  eps      = 0.0,
                  minSize  = 15,
                  maxSize  = 500)

tmp_df <-as.data.frame(fgseaRes[order(pval), ])
tmp_df2<-tmp_df %>% dplyr::filter(pval<0.05)

head(fgseaRes[order(padj), ],10)

write.table(tmp_df2[,-8], file=paste0(data_dir ,"Hallmark_Cirrhosis_sequin_C1.txt"), row.names = F, sep = "\t", quote=F)
```

```{r}
tmp_hallmark<-read.table(paste0(data_dir ,"Hallmark_Cirrhosis_sequin_C1.txt"), header = T)

plt_H<- ggplot(tmp_hallmark, aes(y = reorder(pathway, NES), x = NES, size = size, color = NES)) +
  geom_point() +
  theme_minimal() +
  scale_color_gradient(low = "blue", high = "red") +
  geom_vline(xintercept = 0, linetype = "dashed", color = "grey") +
  labs(title = "Top Enriched Pathways",
       x = "Normalized Enrichment Score (NES)",
       y = "Pathway",
       size = "Gene Set Size",
       color = "NES") +
  theme(axis.text.y = element_text(angle = 0, hjust = 1))


#ggsave("./Figures/Hallmark_NashRisk_all.pdf", plt_H, dpi=500, width = 10)
```


## GO
```{r}
###Formatting the database###
#GO database
GO <- as.data.frame(msigdbr(species = "Homo sapiens", 
                           category = "C5"))

React <- as.data.frame(msigdbr(species = "Homo sapiens", 
                           category = "C2"))
GO <- rbind(GO, React)

GO.ensembl.ls <- GO %>% 
  #Keep gene ID that match expression data gene ID
  dplyr::select(gs_name, ensembl_gene) %>% 
  #Collapse all genes in each gene set into 1 row each
  group_by(gs_name) %>%
  summarise(all.genes = list(unique(ensembl_gene))) %>%
  #Convert to list
  deframe()
```

```{r}
fgseaRes.GO <- fgsea(pathways = GO.ensembl.ls, 
                  stats    = FC.vec,
                  eps      = 0.0,
                  minSize  = 15,
                  maxSize  = 500)
head(fgseaRes.GO[order(pval), ],10)
```

```{r}
#Collapsing similar pathways
collapsedPathways <- collapsePathways(fgseaRes.GO[order(pval)][padj < 0.01], 
                                      GO.ensembl.ls, FC.vec)

mainPathways <- fgseaRes.GO[pathway %in% collapsedPathways$mainPathways][
                         order(-NES), pathway]
GO.ensembl.ls[mainPathways]
GOtmp<-fgseaRes.GO[fgseaRes.GO$pathway%in%mainPathways,]
```

```{r}
tmp_df <-GOtmp %>%filter(padj <= 0.05)
tmp_df[order(NES), ]

write.table(GOtmp%>%filter(padj <= 0.05) %>% dplyr::select(!leadingEdge), file=paste0(data_dir,"GO_Cirrhosis_sequin_C1.txt"), row.names = F, sep = "\t", quote=F)
```

```{r}

plt_GO<- ggplot(tmp_df, aes(y = reorder(pathway, NES), x = NES, size = size, color = NES)) +
  geom_point() +
  theme_minimal() +
  scale_color_gradient(low = "blue", high = "red") +
  geom_vline(xintercept = 0, linetype = "dashed", color = "grey") +
  labs(title = "Top Enriched Pathways",
       x = "Normalized Enrichment Score (NES)",
       y = "Pathway",
       size = "Gene Set Size",
       color = "NES") +
  theme(axis.text.y = element_text(angle = 0, hjust = 1))


#ggsave("./Figures/GO_Cirrhosis_all.pdf", plt_GO, dpi=500, width = 10)
```

```{r}
GO_tmp <-tmp_df[,-c(8)] %>% mutate(database = c(rep("GO", 14)))
tmp_hallmark<-tmp_hallmark %>% mutate(database = c(rep("Hallmark", 2)))

H_GO <- rbind(tmp_hallmark, GO_tmp)


plt_H_GO2<- ggplot(H_GO, aes(y = reorder(pathway, NES), x = NES, size = size, color = NES)) +
  geom_point() +
  theme_minimal() +
  scale_color_gradient(low = "#428bca", high = "#e35d6a") +
  geom_vline(xintercept = 0, linetype = "dashed", color = "grey") +
  facet_grid(database~., scales = "free_y", space="free") +
  labs(title = "Top Enriched Pathways",
       x = "Normalized Enrichment Score (NES)",
       y = "Pathway",
       size = "Gene Set Size",
       color = "NES") +
  theme(axis.text.y = element_text(angle = 0, hjust = 1))

ggsave("./Figures/GSEA_Cirrhosis_C1.pdf", plt_H_GO2, dpi=500, width = 10)
```
### Hepatocyte Signature score

```{r}
library(edgeR)
require(rstatix)
require(ggpubr)
counts<- as.data.frame(counts(dds_spike, normalized =F))
#counts <- counts %>% dplyr::select(rownames(pDat_NASH_filt)) %>% as.matrix()
#pDat_F4F0 <- pDat_NASH_filt %>% dplyr::filter(NAFLD_Diagnosis_AMC%in%c("F0", "F4"))
#pDat_F4F0$Fibrosis<- droplevels(pDat_F4F0$Fibrosis)
levels(pDat_NASH_filt$Cirrhosis)

counts <- counts %>% as.matrix()

dge <- DGEList(counts = counts, samples = pDat_NASH_filt)
#Convert to TMM for cell-type signature analysis
dge_tmm <- calcNormFactors(dge, method = "TMM")
#Now lets extract the CPM counts if calNorm on CPM and raw counts are the same
CpmTmm_matrix<-as.data.frame(cpm(dge_tmm, log = F))
#Load liver signature df
liver_genes <- read.csv("./Deconv/gini6_perCluster_liver_12102020.csv", row.names = 1)
hep_genes <- rownames(liver_genes[!is.na(liver_genes$Hepatocytes.gini),])
#get counts of only hepatocyte genes
hep_counts<-CpmTmm_matrix %>% dplyr::filter(rownames(CpmTmm_matrix)%in%hep_genes)
#Log transformation
log_cts <- log(CpmTmm_matrix+1)
#select only hepatocyte genes
log_hep_genes <- log_cts %>% filter(rownames(log_cts)%in%hep_genes)
#Get the sum of log transfromed CPMTMM per samples
Sum_log_hep<- as.data.frame(colSums(log_hep_genes)) #%>%  rownames_to_column(var="RNAID")
Sum_log_hep<- Sum_log_hep %>% merge(., pDat_NASH_filt, by='row.names')
colnames(Sum_log_hep)[2]<-'Score'


stat.test <- Sum_log_hep %>%
  rstatix::wilcox_test(Score~Cirrhosis, paired = F) %>%
  add_significance()

stat.test

stat.test <- stat.test %>% add_y_position()
#stat.test$y.position<-c(-0.05)#change to a better location

Nash_fib_plt1 <- Sum_log_hep %>% ggplot(aes(x=Cirrhosis, y=Score)) + 
  geom_boxplot(aes(color=Cirrhosis)) +
  geom_beeswarm(alpha=0.5, dodge.width = 1, cex=0.9, size=0.1)+
  stat_pvalue_manual(stat.test, hide.ns = F,label = "{p.signif}")+
  theme_bw()+ theme(plot.title = element_text(hjust = 0.5), legend.position = "none", axis.title.x=element_blank(), axis.title.y=element_blank())+scale_color_manual(values=c("#428bca", "#e35d6a")) 

Nash_fib_plt1
#ggsave("./Figures/HepSign_boxplot.pdf"), Nash_risk_plt1, dpi=300)
```

### Hepatocyte Signature score: with singscore package 

```{r}
require(singscore)

eranks = rankGenes(CpmTmm_matrix)
epi_score = simpleScore(eranks, hep_genes)
```

```{r}
pDat_NASH_filt$Cirrhosis<-as.factor(pDat_NASH_filt$Cirrhosis)
sig_tmp <- epi_score %>% rownames_to_column(var="RNAID") %>% merge(., pDat_NASH_filt, by.x="RNAID", by.y='row.names')


stat.test <- sig_tmp %>%
  rstatix::wilcox_test(TotalScore~Cirrhosis, paired = F) %>%
  add_significance()

stat.test

stat.test <- stat.test %>% add_y_position()
stat.test$y.position<-c(-0.1)#change to a better location

Nash_Cirrhosis_plt3 <- sig_tmp %>% ggplot(aes(x=Cirrhosis, y=TotalScore)) + 
  geom_boxplot(aes(color=Cirrhosis)) +
  #geom_point(aes(size=0.01))+
  geom_beeswarm(alpha=0.5, dodge.width = 1, cex=0.9, size=0.1)+
  stat_pvalue_manual(stat.test, hide.ns = F,label = "{p.signif}")+ theme_bw()+ theme(plot.title = element_text(hjust = 0.5), legend.position = "none", axis.title.x=element_blank(), axis.title.y=element_blank())+scale_color_manual(values=c("#428bca", "#e35d6a"))

Nash_Cirrhosis_plt3

#ggsave(("./Figures/Singscore_HepSignal_Riskboxplot.pdf"), Nash_risk_plt3, dpi=300)
```

```{r}
signature_plot<- ggarrange(Nash_fib_plt1, Nash_Cirrhosis_plt3,   labels = c("A ", "B "), 
                           font.label = list(size = 10, color = "black", face = "bold", family = NULL),
                           align=c("hv"), label.x = c(-0.02, -0.01), label.y = c(1, 1) 
                           )

signature_plot

ann_sign_plt<-annotate_figure(signature_plot, left = "hepatocyte signature score", fig.lab.size=10)
ann_sign_plt
ggsave(("./Figures/HepSignal_Cirrhosis_C1_boxplot.pdf"), ann_sign_plt, dpi=500)
```

